oauth2-server/accounts/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('user-info/', views.UserRetrieve.as_view()),
]

oauth2-server/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('user-update/', views.UserUpdate.as_view(), name='user-update'),
]

oauth2-server/oauth2_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oauth2_provider.urls')),
    path('', include('allauth.urls')),
    path('', include('accounts.urls')),
    path('api/', include('accounts.api.urls')),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
]

oauth2-server/accounts/api/views.py
from rest_framework.generics import RetrieveAPIView

from .serializers import UserSerializer


class UserRetrieve(RetrieveAPIView):
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user

oauth2-server/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView


class UserUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'registration/user_update.html'
    fields = ['username', 'email', 'first_name', 'last_name']
    success_url = reverse_lazy('main')

    def get_object(self, queryset=None):
        return self.request.user

oauth2-server/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>OAuth2 server</title>
</head>
<body>
<div>
  <h1>OAuth2 server</h1>
  {% block content %}{% endblock %}
</div>
</body>
</html>

oauth2-server/templates/main.html
{% extends 'base.html' %}

{% block content %}
  {% if user.is_authenticated %}
    <p>{{ user }}</p>
    <ul>
      <li><a href="{% url 'oauth2_provider:list' %}">Applications</a></li>
      <li><a href="{% url 'oauth2_provider:authorized-token-list' %}">Authorized tokens</a></li>
      <li><a href="{% url 'accounts:user-update' %}">User update</a></li>
      <li><a href="{% url 'account_logout' %}">Log out</a></li>
    </ul>
  {% else %}
    <ul>
      <li><a href="{% url 'account_login' %}">Log in</a></li>
      <li><a href="{% url 'account_signup' %}">Sign up</a></li>
    </ul>
  {% endif %}
{% endblock %}